pipeline {
    agent any

    triggers {
        githubPush()
    }
	
    environment {
	    USER_NAME= "vhazarathnaidu"
		current_branch="${env.GIT_BRANCH}"
        BRANCH_NAME= "${env.GIT_BRANCH}".replace('origin/', '')
    }

    stages {
	stage('Pre-Build: Create Jenkins Agents') {
      
    steps {
        script {
            echo "creating agents using scriptfile..."
           if(isUnix()){
		   sh 'D:/sfts/Agents/agents.bat'
		   }else{
		   bat 'D:\\sfts\\Agents\\agents.bat'
		   }

        }
    }
}
      stage('wait for agents') {
    steps {
        script {
            timeout(time: 2, unit: 'MINUTES') {

                def agents = ['java-agent', 'python-agent', 'nodejs-agent']

                for (nodeLabel in agents) {
                    echo "waiting for ${nodeLabel} to come online..."

                    waitUntil {
                        try {
                            node(nodeLabel) {
                                echo "${nodeLabel} is online!"
                            }
                            return true
                        } catch (Exception e) {
                            return false
                        }
                    }
                }
            }
        }
    }
}

        stage('Checkout Code') {
            steps {
				echo "Current branch name: ${env.BRANCH_NAME}"
				echo "Current branch name: ${env.GIT_BRANCH}" 
				echo "username: ${env.USER_NAME}"
			   git(
                    url: "https://github.com/${env.USER_NAME}/git-branching-stratey.git",
                    branch: "${env.BRANCH_NAME}"
                )
            }
        }

        stage('Build Java Project') {
		 agent { label 'java' }
            steps {
                dir("Jenkins/Multi-dir-project/java") {
                    script {
                        if (isUnix()) {
							sh """ 
								echo "Compailing Java program..."
								javac Hello.java
								javac Main.java
							"""
                        } else {
						    
                            bat "javac Hello.java"
							bat "javac Main.java"
                        }
                    }
                }
            }
        }
		stage('deploy java'){
		 agent { label 'java' }
		steps{
		     dir("Jenkins/Multi-dir-project/java") {
                    script {
                        if (isUnix()) {
						
                            sh """ 
								echo "Running Java program in unix shell ..."
								java --version
								java Main
								echo "Completed ..."
							"""
                        }
						else {
						echo "Running Java program in windows shell..."
                            bat "java Hello"
							bat "java Main"
                    }
                }
            }
			}
			}
			stage('deploy python'){
			 agent { label 'python' }
			steps{
			dir("Jenkins/Multi-dir-project/python") {
                    script {
                        if (isUnix()) {
                            sh """
							   echo "Running python program in unix shell..."
							   python Hello.py
							
							"""
                        }
						else {
						    echo "Running python program in windows shell...."
                            bat "python Hello.py"
                    }
                }
            }
			}
			}
			stage('deploy nodejs'){
			 agent { label 'nodejs' }
			steps{
			dir("Jenkins/Multi-dir-project/node") {
                    script {
                        if (isUnix()) {
						        
                            sh """
							echo "Running Nodejs program in unix shell ..."
							node Hello.js
							
							"""
                        }
						else {
						echo "Running Nodejs program in windows shell..."
                            bat "node Hello.js"
                    }
                }
            }
			}
			}
			
		}
	}

