pipeline {
    agent any

    triggers {
        githubPush()
    }

    environment {
	    USER_NAME= "vhazarathnaidu"
        BRANCH_NAME= "${env.GIT_BRANCH}".replace('origin/', '')
    }

    stages {

        stage('Checkout Code') {
            steps {
				echo "Current branch name: ${env.BRANCH_NAME}"
				echo "Current branch name: ${env.GIT_BRANCH}" 
				echo "username: ${env.USER_NAME}"
			   git(
                    url: "https://github.com/${env.USER_NAME}/git-branching-stratey.git",
                    branch: "${env.BRANCH_NAME}"
                )
            }
        }

        stage('Build Java Project') {
            steps {
                dir("Jenkins/Multi-dir-project/java") {
                    script {
                        if (isUnix()) {
							sh """ 
								echo "Compailing Java..."
								javac Hello.java
								javac Main.java
							"""
                        } else {
						    
                            bat "javac Hello.java"
							bat "javac Main.java"
                        }
                    }
                }
            }
        }
		stage('deploy'){
		steps{
		     dir("Jenkins/Multi-dir-project/java") {
                    script {
                        if (isUnix()) {
						
                            sh """ 
								echo "Running Java program in unix shell ..."
								java --version
								java Main
								echo "Completed ..."
							"""
                        }
						else {
						echo "Running Java program in windows shell..."
                            bat "java Hello"
							bat "java Main"
                    }
                }
            }
			dir("Jenkins/Multi-dir-project/python") {
                    script {
                        if (isUnix()) {
                            sh """
							   echo "Running python program in unix shell..."
							   python Hello.py
							
							"""
                        }
						else {
						    echo "Running python program in windows shell...."
                            bat "python Hello.py"
                    }
                }
            }
			dir("Jenkins/Multi-dir-project/node") {
                    script {
                        if (isUnix()) {
						        
                            sh """
							echo "Running Nodejs program in unix shell ..."
							node Hello.js
							
							"""
                        }
						else {
						echo "Running Nodejs program in windows shell..."
                            bat "node Hello.js"
                    }
                }
            }
			
		}
	}

  }
}