#!/usr/bin/env bash

# VARIABLES

# REGION
REGION="us-east-1"
AZ="us-east-1a"

# VPC
# VPC_NAMES=["ntier-1" "ntier-2"]
# VPC_CIDRS=("10.10.0.0/16" "10.20.0.0/16")
VPC_NAMES=("ntier1-vpc")
VPC_CIDRS=("10.10.0.0/16")
# SUBNETS
# PUBLIC_SUBNET_CIDRS=("10.10.1.0/24" "10.20.1.0/24")
# PRIVATE_SUBNET_CIDRS=("10.10.2.0/24" "10.20.2.0/24")
PUBLIC_SUBNET_CIDRS=("10.10.1.0/24")
PRIVATE_SUBNET_CIDRS=("10.10.2.0/24")
# PUBLIC_SUBNET_NAME=("ntier1-public" "ntier2-public")
PUBLIC_SUBNET_NAME="ntier1-public"
# PUBLIC_SUBNET_NAME=("ntier1-private" "ntier2-private")
PRIVATE_SUBNET_NAME="ntier1-private"

# INTERNET GATEWAY
IGW_NAME="ntier1-igw"
# IGW_NAME=("ntier1-igw" "ntier2-igw")

# Route table

PUBLIC_SUBNET_COUNT=1
PRIVATE_SUBNET_COUNT=1

# ROUTE TABLE NAMES
PUBLIC_RT_BASE_NAME="ntier1-public-rt"
PRIVATE_RT_BASE_NAME="ntier1-private-rt"

# PUBLIC_RT_BASE_NAME=("ntier1-public-rt" "ntier2-public-rt"
# PRIVATE_RT_BASE_NAME=("ntier1-private-rt" "ntier2-private-rt")

# EC2
INSTANCE_TYPE="t3.micro"
INSTANCE_TAG_NAME="web-1"
# INSTANCE_TAG_NAME=("web-1" "web-2")
KEY_NAME="hazarath"

# SECURITY GROUP
SG_TAG_NAME="ntier1sg"
# SG_TAG_NAME=("ntier1sg" "ntier2sg")
SG_COUNT=1
SECURITY_GROUP_ID_TCP_CIDR_RANGE="0.0.0.0/0"
SG_PORTS="22 80 9091 8080"
# USER_DATA_FILE="jenkins/agents/setup-jenkins_java_agent.sh"
USER_DATA_FILE="jenkins/agents/setup-docker_agent.sh"
