#!/usr/bin/env bash

# VARIABLES

# REGION
REGION="us-east-1"
AZ="us-east-1a"

# VPC
VPC_CIDR="10.10.0.0/16"
VPC_NAME="ntier1-vpc"

# SUBNETS
#PUBLIC_SUBNET_CIDR=["10.10.1.0/24", "10.10.2.0/24"]
PUBLIC_SUBNET_CIDR="10.10.1.0/24"
PRIVATE_SUBNET_CIDR="10.10.2.0/24"
PUBLIC_SUBNET_NAME="public-subnet"
PRIVATE_SUBNET_NAME="private-subnet"

# INTERNET GATEWAY
IGW_NAME="ntier1-igw"

# EC2
INSTANCE_TYPE="t3.micro"
INSTANCE_TAG_NAME="web-1"
KEY_NAME="hazarath"

# SECURITY GROUP
SG_TAG_NAME="ntier1sg"
SECURITY_GROUP_ID_TCP_CIDR_RANGE="0.0.0.0/0"