apiVersion: apps/v1
kind: Deployment
metadata: {{- toYaml .Values.metadata.labels | nindent 2}}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector: {{- .Values.selector | toYaml | nindent 4 }}
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata: {{- toYaml .Values.metadata | nindent 6 }}
    spec:
      containers: {{ .Values.containers | toYaml | nindent 8 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports: {{ .Values.port | toYaml | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}