apiVersion: v1
kind: Service
metadata: 
  name: {{.Values.name }}-service
spec: 
  type: {{.Values.service.type }}
  selector: {{- toYaml .Values.labels | nindent 4 }}
  ports: {{- toYaml .Values.ports | nindent 4 }}