apiVersion: v1
kind: Service
metadata: {{ toYaml .Values.metadata.labels | nindent 2 }}-service
spec: {{- toYaml .Values.service | nindent 2 }}
  selector: {{- toYaml .Values.selector.matchLabels | nindent 4 }}
  ports: {{- toYaml .Values.ports | nindent 4 }}