pipeline {
    agent any

    triggers {
        pollSCM('H/2 * * * *')
    }

    environment {
	    USER_NAME= "vhazarathnaidu"
        BRANCH_NAME= "${env.GIT_BRANCH ?: 'future-ep-004-task-002'}"
    }

    stages {

        stage('Checkout Code') {
            steps {
				echo "Current branch name: ${env.BRANCH_NAME}"
				echo "Current branch name: ${env.GIT_BRANCH}"
                git url:"https://github.com/${env.USER_NAME}/git-branching-stratey.git,branch:${env.GIT_BRANCH}"
            }
        }

        stage('Build Java Project') {
            steps {
                dir("Jenkins/java") {
                    script {
                        if (isUnix()) {
                            sh "javac Hello.java"
							sh "javac Main.java"
                        } else {
                            bat "javac Hello.java"
							bat "javac Main.java"
                        }
                    }
                }
            }
        }
		stage('deploy'){
		steps{
		     dir("Jenkins/java") {
                    script {
                        if (isUnix()) {
                            sh "java Hello"
							sh "java Main"
                        }
						else {
                            bat "java Hello"
							bat "java Main"
                    }
                }
            }
			dir("Jenkins/python") {
                    script {
                        if (isUnix()) {
                            sh "python Hello.py"
                        }
						else {
                            bat "python Hello.py"
                    }
                }
            }
			dir("Jenkins/node") {
                    script {
                        if (isUnix()) {
                            sh "node Hello.js"
                        }
						else {
                            bat "node Hello.js"
                    }
                }
            }
			
		}
	}

  }
}