pipeline{
  agent any
  triggers {
   cron('* * * * *')
  }
  stages{
   stage('git'){
      steps{
      git url:'https://github.com/vhazarathnaidu/git-branching-stratey.git',branch:'main'
	  }
   }
   stage('build') {
            steps {
                dir('Jenkins/java') {
                    bat 'javac Main.java'
                    bat 'java Main'
                }
                dir('Jenkins/python') {
                    bat 'python Hello.py'
                }
				dir('Jenkins/node'){
				bat 'node Hello.js'
				}
	 }
	
  }
  }
  }